import type { Boat } from "@/components/boat/BoatProvider";
import type { CategoryRow } from "@/components/categories/CategoriesManager";
import type {
  EngineDetail,
  EngineItemRow,
  EngineLogRow,
  EngineReadingRow,
} from "@/components/engines/EngineSheet";
import type { EngineSummary } from "@/components/engines/EnginesTab";
import type { CategorySummary, EquipmentSummary } from "@/components/equipment/EquipmentTab";
import type { BoatModelData } from "@/components/boat-3d/BoatModel3D";
import type { BoatModelOption } from "@/lib/boat-models";

import { DEV_BOAT_ID } from "../DevShell";
import { SAMPLE_CATEGORIES } from "../sample-data";

const NOW = "2026-09-02T10:00:00+00:00";

export const SAMPLE_BOAT: Boat = {
  id: DEV_BOAT_ID,
  organization_id: null,
  name: "Xaman",
  navigation_zone: "offshore",
  inbox_token: "e1ee647f8965",
  builder: "Marsaudon Composites",
  model: "ORC 50",
  hull_number: "25",
  registration: "HY 512340",
  year: 2019,
  type: "catamaran",
  flag: "France",
  home_port: "Hyères",
  sail_number: "FRA 2519",
  length_m: 15.24,
  beam_m: 8.2,
  draft_m: 1.35,
  photo_path: null,
  notes: "Dérives sabres carbone, haubans textiles. Deux Yanmar 4JH45 + annexe Yamaha 15.",
  checklist_template_id: "00000000-0000-4000-8000-000000000001",
  external_ref: "xaman",
  created_by: null,
  updated_by: null,
  created_at: NOW,
  updated_at: NOW,
};

export const SAMPLE_ENGINES: EngineSummary[] = [
  {
    id: "00000000-0000-4000-8000-00000000e001",
    label: "Moteur SB",
    position: "starboard",
    propulsion: "saildrive",
    brand: "Yanmar",
    model: "4JH45",
    installedAt: "2021-04-12",
    isActive: true,
    tracksHours: true,
    hours: 1256,
    readAt: "2026-08-28",
    linkedItems: 6,
  },
  {
    id: "00000000-0000-4000-8000-00000000e002",
    label: "Moteur BB",
    position: "port",
    propulsion: "saildrive",
    brand: "Yanmar",
    model: "4JH45",
    installedAt: "2021-04-12",
    isActive: true,
    tracksHours: true,
    hours: 1208,
    readAt: "2026-06-10",
    linkedItems: 6,
  },
  {
    id: "00000000-0000-4000-8000-00000000e003",
    label: "Annexe",
    position: "outboard",
    propulsion: "outboard",
    brand: "Yamaha",
    model: "F15",
    installedAt: null,
    isActive: true,
    tracksHours: false,
    hours: null,
    readAt: null,
    linkedItems: 2,
  },
  {
    id: "00000000-0000-4000-8000-00000000e004",
    label: "Ancien moteur SB",
    position: "starboard",
    propulsion: "saildrive",
    brand: "Volvo",
    model: "D2-40",
    installedAt: "2012-03-01",
    isActive: false,
    tracksHours: true,
    hours: 3890,
    readAt: "2021-03-30",
    linkedItems: 0,
  },
];

/** The template's own word for each system, as the seeds write it (`orc50-checklist.json`). */
const CATEGORY_REFS: Record<string, string> = {
  engines: "engines",
  daggerboards: "daggerboards_rudders",
  sails: "sails_rigging",
  hull: "hull_deck",
  electronics: "electronics_nav",
  energy: "energy",
  plumbing: "plumbing_systems",
  safety: "safety",
};

export const SAMPLE_EQUIPMENT_CATEGORIES: CategorySummary[] = SAMPLE_CATEGORIES.map((c) => ({
  id: c.id,
  name: c.name,
  color: c.color,
  icon: c.icon,
  externalRef: CATEGORY_REFS[c.id] ?? null,
}));

export const SAMPLE_EQUIPMENT: EquipmentSummary[] = [
  {
    id: "q1",
    name: "Winch Andersen 62ST",
    brand: "Andersen",
    model: "62ST",
    quantity: 4,
    categoryId: "sails",
    installedAt: "2019-05-01",
    removedAt: null,
  },
  {
    id: "q2",
    name: "Enrouleur génois",
    brand: "Facnor",
    model: "LS290",
    quantity: 1,
    categoryId: "sails",
    installedAt: null,
    removedAt: null,
  },
  {
    id: "q3",
    name: "Pilote automatique",
    brand: "B&G",
    model: "NAC-3",
    quantity: 1,
    categoryId: "electronics",
    installedAt: "2019-05-01",
    removedAt: null,
  },
  {
    id: "q4",
    name: "Radar",
    brand: "B&G",
    model: "Halo 20+",
    quantity: 1,
    categoryId: "electronics",
    installedAt: "2022-03-15",
    removedAt: null,
  },
  {
    id: "q5",
    name: "Batteries service lithium",
    brand: "Victron",
    model: "200 Ah",
    quantity: 3,
    categoryId: "energy",
    installedAt: "2023-02-01",
    removedAt: null,
  },
  {
    id: "q6",
    name: "Dessalinisateur",
    brand: "Dessalator",
    model: "D100",
    quantity: 1,
    categoryId: "plumbing",
    installedAt: null,
    removedAt: null,
  },
  {
    id: "q7",
    name: "Radeau de survie",
    brand: "Plastimo",
    model: "Transocean 8",
    quantity: 1,
    categoryId: "safety",
    installedAt: "2024-04-01",
    removedAt: null,
  },
  // The lines the 3D model reads: the boat is drawn with the boards, the skirts, the sprit and
  // the sail areas the carnet records, not from a generic catamaran (E2-8).
  {
    id: "q9",
    name: "Dérives sabres carbone",
    brand: "Marsaudon Composites",
    model: null,
    quantity: 2,
    categoryId: "daggerboards",
    installedAt: "2019-05-01",
    removedAt: null,
  },
  {
    id: "q10",
    name: "Safrans suspendus",
    brand: null,
    model: null,
    quantity: 2,
    categoryId: "daggerboards",
    installedAt: "2019-05-01",
    removedAt: null,
  },
  {
    id: "q11",
    name: "Jupes de flotteur allongées",
    brand: null,
    model: null,
    quantity: 2,
    categoryId: "hull",
    installedAt: "2019-05-01",
    removedAt: null,
    specs: { allongement_cm: 60 },
  },
  {
    id: "q12",
    name: "Grand-voile (GV)",
    brand: "Incidence",
    model: "Hydranet",
    quantity: 1,
    categoryId: "sails",
    installedAt: "2019-05-01",
    removedAt: null,
    specs: { surface_m2: 88, tissu: "Hydranet" },
  },
  {
    id: "q13",
    name: "J1 (Génois)",
    brand: "Incidence",
    model: "Hydranet",
    quantity: 1,
    categoryId: "sails",
    installedAt: "2019-05-01",
    removedAt: null,
    specs: { surface_m2: 60 },
  },
  {
    id: "q14",
    name: "Code 0 (J0) sur bout-dehors",
    brand: "Incidence",
    model: "PX Black",
    quantity: 1,
    categoryId: "sails",
    installedAt: "2021-06-01",
    removedAt: null,
    specs: { surface_m2: 87.5 },
  },
  {
    id: "q15",
    name: "Panneaux solaires monocristallins",
    brand: "Victron",
    model: null,
    quantity: 6,
    categoryId: "energy",
    installedAt: "2023-02-01",
    removedAt: null,
    specs: { puissance_w: 990, emplacement: "Sur bossoirs" },
  },
  {
    id: "q16",
    name: "Guindeau électrique",
    brand: "Lofrans",
    model: null,
    quantity: 1,
    categoryId: "hull",
    installedAt: "2019-05-01",
    removedAt: null,
  },
  {
    id: "q17",
    name: "Ancre",
    brand: "Spade",
    model: null,
    quantity: 1,
    categoryId: "hull",
    installedAt: "2019-05-01",
    removedAt: null,
    specs: { poids_kg: 25 },
  },
  {
    id: "q18",
    name: "Starlink",
    brand: "Starlink",
    model: "RUTX10",
    quantity: 1,
    categoryId: "electronics",
    installedAt: "2024-01-15",
    removedAt: null,
  },
  {
    id: "q8",
    name: "Ancien pilote",
    brand: "Raymarine",
    model: "EV-1",
    quantity: 1,
    categoryId: "electronics",
    installedAt: "2019-05-01",
    removedAt: "2023-02-10",
  },
];

export const SAMPLE_ENGINE_DETAIL: EngineDetail = {
  id: "00000000-0000-4000-8000-00000000e001",
  label: "Moteur SB",
  position: "starboard",
  propulsion: "saildrive",
  brand: "Yanmar",
  model: "4JH45",
  serial: "E12345",
  installedAt: "2021-04-12",
  notes: null,
  isActive: true,
  tracksHours: true,
  counterResetAt: null,
};

export const SAMPLE_ENGINE_ITEMS: EngineItemRow[] = [
  {
    id: "i1",
    label: "Vidange huile moteur + filtre à huile — Moteur SB",
    categoryId: "engines",
    intervalMonths: 12,
    intervalHours: 250,
    status: "overdue",
    daysRemaining: 60,
    hoursRemaining: -426,
    hasCounter: true,
    lastCompletedAt: "2026-03-06",
    lastEngineHours: 580,
  },
  {
    id: "i2",
    label: "Filtres à gasoil (primaire + secondaire) — Moteur SB",
    categoryId: "engines",
    intervalMonths: 12,
    intervalHours: 250,
    status: "soon",
    daysRemaining: 120,
    hoursRemaining: 44,
    hasCounter: true,
    lastCompletedAt: "2026-03-06",
    lastEngineHours: 1050,
  },
  {
    id: "i3",
    label: "Anode de collecteur — Moteur SB",
    categoryId: "engines",
    intervalMonths: 12,
    intervalHours: null,
    status: "never",
    daysRemaining: 365,
    hoursRemaining: null,
    hasCounter: true,
    lastCompletedAt: null,
    lastEngineHours: null,
  },
  {
    id: "i4",
    label: "Courroie alternateur — Moteur SB",
    categoryId: "engines",
    intervalMonths: 24,
    intervalHours: 500,
    status: "ok",
    daysRemaining: 540,
    hoursRemaining: 300,
    hasCounter: true,
    lastCompletedAt: "2026-03-06",
    lastEngineHours: 1056,
  },
];

export const SAMPLE_ENGINE_READINGS: EngineReadingRow[] = [
  {
    id: "r1",
    hours: 1256,
    readAt: "2026-08-28",
    source: "manual",
    note: null,
    byName: "Xavier Marin",
    updatedAt: NOW,
  },
  {
    id: "r2",
    hours: 1234,
    readAt: "2026-08-20",
    source: "maintenance_log",
    note: "Check niveaux",
    byName: "Xavier Marin",
    updatedAt: NOW,
  },
  {
    id: "r3",
    hours: 1056,
    readAt: "2026-03-06",
    source: "import",
    note: null,
    byName: "Xavier Marin",
    updatedAt: NOW,
  },
  {
    id: "r4",
    hours: 580,
    readAt: "2025-03-06",
    source: "import",
    note: "Vidange",
    byName: null,
    updatedAt: NOW,
  },
];

export const SAMPLE_ENGINE_LOGS: EngineLogRow[] = [
  {
    id: "l1",
    title: "Vidange + entretien complet (2 moteurs)",
    performedAt: "2026-03-06",
    status: "done",
    cost: 620,
    contactName: "Motoriste Yanmar Hyères",
  },
  {
    id: "l2",
    title: "Check niveaux",
    performedAt: "2026-08-20",
    status: "done",
    cost: null,
    contactName: null,
  },
];

export const SAMPLE_CATEGORY_ROWS: CategoryRow[] = [
  ...SAMPLE_CATEGORIES.map((c, index) => ({
    id: c.id,
    name: c.name,
    color: c.color,
    icon: c.icon as string | null,
    isActive: true,
    activeItems: [13, 6, 23, 12, 10, 7, 10, 9][index] ?? 0,
    updatedAt: NOW,
  })),
  {
    id: "old",
    name: "Annexe et hors-bord",
    color: "#63748A",
    icon: null,
    isActive: false,
    activeItems: 0,
    updatedAt: NOW,
  },
];

/**
 * A slice of the model catalogue (D69), enough to exercise every branch of the suggestions:
 * two yards sharing a model name, a row with no draft because the series has two keels, and one
 * with nothing but a length.
 */
export const SAMPLE_BOAT_MODELS: BoatModelOption[] = [
  {
    id: "00000000-0000-4000-8000-0000000000b0",
    builder: "Marsaudon Composites",
    model: "ORC 50",
    boatType: "catamaran",
    yearFrom: 2017,
    yearTo: null,
    lengthM: 15.24,
    beamM: 8.2,
    draftM: 1.35,
  },
  {
    id: "00000000-0000-4000-8000-0000000000b1",
    builder: "Bénéteau",
    model: "Oceanis 46.1",
    boatType: "monohull_sail",
    yearFrom: 2018,
    yearTo: null,
    lengthM: 14.6,
    beamM: 4.5,
    draftM: null,
  },
  {
    id: "00000000-0000-4000-8000-0000000000b2",
    builder: "Bénéteau",
    model: "First 40",
    boatType: "monohull_sail",
    yearFrom: 2010,
    yearTo: 2015,
    lengthM: 12.0,
    beamM: 3.85,
    draftM: null,
  },
  {
    id: "00000000-0000-4000-8000-0000000000b3",
    builder: "Lagoon",
    model: "Lagoon 42",
    boatType: "catamaran",
    yearFrom: 2016,
    yearTo: null,
    lengthM: 12.8,
    beamM: 7.7,
    draftM: 1.25,
  },
  {
    id: "00000000-0000-4000-8000-0000000000b4",
    builder: "Jeanneau",
    model: "Merry Fisher 795",
    boatType: "motor",
    yearFrom: 2019,
    yearTo: null,
    lengthM: 7.6,
    beamM: null,
    draftM: null,
  },
];

/**
 * The 3D model's own sample (E2-8): the same boat, its systems, and a handful of points in
 * every state so the pins, the badges and the « rien à faire » case are all on screen at once.
 */
export const SAMPLE_MODEL: BoatModelData = {
  shape: {
    type: SAMPLE_BOAT.type ?? "catamaran",
    lengthM: SAMPLE_BOAT.length_m,
    beamM: SAMPLE_BOAT.beam_m,
    draftM: SAMPLE_BOAT.draft_m,
    engines: SAMPLE_ENGINES.filter((engine) => engine.isActive).map((engine) => ({
      id: engine.id,
      position: engine.position,
    })),
  },
  categories: SAMPLE_EQUIPMENT_CATEGORIES.map((category) => ({
    id: category.id,
    externalRef: category.externalRef ?? null,
  })),
  equipment: SAMPLE_EQUIPMENT.filter((item) => !item.removedAt).map((item) => ({
    id: item.id,
    name: item.name,
    brand: item.brand,
    model: item.model,
    quantity: item.quantity,
    categoryId: item.categoryId,
    externalRef: item.externalRef ?? null,
    specs: item.specs ?? null,
  })),
  points: [
    {
      id: "p1",
      label: "Contrôle du gréement dormant",
      state: "overdue",
      daysRemaining: -126,
      hoursRemaining: null,
      hasCounter: true,
      categoryId: "sails",
      engineId: null,
    },
    {
      id: "p2",
      label: "Lattes et chariots de grand-voile",
      state: "soon",
      daysRemaining: 12,
      hoursRemaining: null,
      hasCounter: true,
      categoryId: "sails",
      engineId: null,
    },
    {
      id: "p3",
      label: "Chaîne de mouillage : marquage et manille",
      state: "overdue",
      daysRemaining: -18,
      hoursRemaining: null,
      hasCounter: true,
      categoryId: "hull",
      engineId: null,
    },
    {
      id: "p4",
      label: "Anodes de saildrive",
      state: "soon",
      daysRemaining: 21,
      hoursRemaining: 40,
      hasCounter: true,
      categoryId: "engines",
      engineId: SAMPLE_ENGINES[0]?.id ?? null,
    },
    {
      id: "p5",
      label: "Vidange moteur",
      state: "ok",
      daysRemaining: 180,
      hoursRemaining: 210,
      hasCounter: true,
      categoryId: "engines",
      engineId: SAMPLE_ENGINES[1]?.id ?? null,
    },
    {
      id: "p6",
      label: "Joints de dérives",
      state: "never",
      daysRemaining: null,
      hoursRemaining: null,
      hasCounter: true,
      categoryId: "daggerboards",
      engineId: null,
    },
    {
      id: "p7",
      label: "Percussion du radeau de survie",
      state: "soon",
      daysRemaining: 27,
      hoursRemaining: null,
      hasCounter: true,
      categoryId: "safety",
      engineId: null,
    },
    {
      id: "p8",
      label: "Filtres du dessalinisateur",
      state: "ok",
      daysRemaining: 95,
      hoursRemaining: null,
      hasCounter: true,
      categoryId: "plumbing",
      engineId: null,
    },
  ],
  engines: SAMPLE_ENGINES.map((engine) => ({ id: engine.id, label: engine.label })),
};
